export const MESSAGES = {
    LOGIN_LOADED: 'ACTA_LOGIN_LOADED',
    GROUPS_LOADED: 'ACTA_GROUPS_LOADED',
    GROUP_SELECTED: 'ACTA_GROUP_SELECTED',
    STUDENTS_LOADED: 'ACTA_STUDENTS_LOADED',
    AUTHENTICATE_USER: 'ACTA_AUTHENTICATE_USER',
    AUTHENTICATION_FAILED: 'ACTA_AUTHENTICATION_FAILED'
}